// Execute GET request to https://api.webscraper.io/api/v1/scraping-job/<SCRAPING JOB ID>/csv?api_token=<YOUR API TOKEN>

// NOTE! We recommend using JSON format since multiple CSV notations are
// being used by different products. For example:
// CSV Standard: https://tools.ietf.org/html/rfc4180
// MS Excel cannot handle escape sequences from the CSV standard
// PHP has incorrect default implementation. See https://wiki.php.net/rfc/kill-csv-escaping

// response - A CSV file
web-scraper-order,title,Color
1494492462-1,Fluffy Cat,blue
1494492462-1,Fluffy Dog,white
