{
	"success": true,
	"data": [
		{
			"url": "https://webscraper.io/empty",
			"type": "empty",
		},
		{
			"url": "https://webscraper.io/failed",
			"type": "failed",
		},
		{
		...
		}
	],
	"current_page": 1,
	"last_page": 1,
	"total": 5,
	"per_page": 100,
}
