name: Documentation Spellcheck

on: [push]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.40.0
        with:
          config_path: ".github/workflows/spellcheck.yml"
          task_name: Markdown

      - name: Upload spellcheck results
        uses: actions/upload-artifact@v3
        with:
          name: Spellcheck Results
          path: spellcheck-output.txt
